import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import { HomeNavbar } from "@/components/ui/home_nav";
import { Footer } from "@/components/home/Footer";
import { AccountSideBar } from "@/components/account/Sidebar";
import { MobileDashboardNavigation } from "@/components/mobile/MobileDashboardNavigation";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <div className="min-h-screen grid md:grid-cols-4 gap-6 mt-[calc(var(--nav-height))] container-x grid-cols-1">
        <AccountSideBar />
        <div className="col-span-3">{children}</div>
        <MobileDashboardNavigation />
      </div>
    </main>
  );
}
