import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import { HomeNavbar } from "@/components/ui/home_nav";
import { Footer } from "@/components/home/Footer";
import { Toaster } from "@/components/ui/sonner";
import { MobileNavigationTab } from "@/components/mobile/navigation";
import { TopBar } from "@/components/mobile/topbar";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        inter.variable,
      )}
    >
      <div className="min-h-full pb-[calc(var(--mobile-nav-height)+10px)] lg:pb-0 bg-background flex flex-col">
        <HomeNavbar />
        <TopBar />
        <Toaster />
        {children}
        <MobileNavigationTab />
        <Footer />
      </div>
    </main>
  );
}
